/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./node_modules/webcc-ui-components/**/*.js",
    "./src/**/*.{js,vue,ts}",
    "./nuxt.config.{js,ts}",
  ],
  theme: {
    extend: {
      colors: {
        cta: {
          DEFAULT: "var(--color-cta);",
          active: "var(--color-cta-active)",
          contrast: "var(--color-cta-contrast)",
          hover: "var(--color-cta-hover)",
          light: {
            DEFAULT: "var(--color-cta-light)",
            active: "var(--color-cta-light-active)",
            contrast: "var(--color-cta-light-contrast)",
            hover: "var(--color-cta-light-hover)",
          },
        },
        hlt: {
          DEFAULT: "var(--color-hlt)",
          active: "var(--color-hlt-active)",
          contrast: "var(--color-hlt-contrast)",
          hover: "var(--color-hlt-hover)",
          light: {
            DEFAULT: "var(--color-hlt-light)",
            active: "var(--color-hlt-light-active)",
            contrast: "var(--color-hlt-light-contrast)",
            hover: "var(--color-hlt-light-hover)",
          },
        },
        thm: {
          DEFAULT: "var(--color-thm)",
          active: "var(--color-thm-active)",
          contrast: "var(--color-thm-contrast)",
          hover: "var(--color-thm-hover)",
          light: {
            DEFAULT: "var(--color-thm-light)",
            active: "var(--color-thm-light-active)",
            contrast: "var(--color-thm-light-contrast)",
            hover: "var(--color-thm-light-hover)",
          },
        },
        bgr: {
          DEFAULT: "var(--color-bgr)",
          100: "var(--color-bgr100)",
          200: "var(--color-bgr200)",
          300: "var(--color-bgr300)",
          400: "var(--color-bgr400)",
          500: "var(--color-bgr500)",
          600: "var(--color-bgr600)",
          700: "var(--color-bgr700)",
          800: "var(--color-bgr800)",
          900: "var(--color-bgr900)",
        },
        txt: {
          DEFAULT: "var(--color-txt)",
          dim: "var(--color-txt-dim)",
          stress: "var(--color-txt-stress)",
          100: "var(--color-txt100)",
          200: "var(--color-txt200)",
          300: "var(--color-txt300)",
          400: "var(--color-txt400)",
          500: "var(--color-txt500)",
          600: "var(--color-txt600)",
          700: "var(--color-txt700)",
          800: "var(--color-txt800)",
          900: "var(--color-txt900)",
          link: {
            DEFAULT: "var(--color-txt-link)",
            active: "var(--color-txt-link-active)",
            contrast: "var(--color-txt-link-contrast)",
            hover: "var(--color-txt-link-hover)",
          },
        },
        inf: {
          DEFAULT: "var(--color-inf)",
          active: "var(--color-inf-active)",
          contrast: "var(--color-inf-contrast)",
          hover: "var(--color-inf-hover)",
          light: "var(--color-inf-light)",
          text: "var(--color-inf-text)",
        },
        suc: {
          DEFAULT: "var(--color-suc)",
          active: "var(--color-suc-active)",
          contrast: "var(--color-suc-contrast)",
          hover: "var(--color-suc-hover)",
          light: "var(--color-suc-light)",
          text: "var(--color-suc-text)",
        },
        wrn: {
          DEFAULT: "var(--color-wrn)",
          active: "var(--color-wrn-active)",
          contrast: "var(--color-wrn-contrast)",
          hover: "var(--color-wrn-hover)",
          light: "var(--color-wrn-light)",
          text: "var(--color-wrn-text)",
        },
        err: {
          DEFAULT: "var(--color-err)",
          active: "var(--color-err-active)",
          contrast: "var(--color-err-contrast)",
          hover: "var(--color-err-hover)",
          light: "var(--color-err-light)",
          text: "var(--color-err-text)",
        },
        offer: "var(--color-offer)",
        supplier: "var(--color-supplier)",
        accommodation: "var(--color-accommodation)",
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
